### ISSUE TITLE
Issue Connecting

### ISSUE THREAD

**Issue by ColtraneNadler** [jsyqrt/psotify#2]
```
Traceback (most recent call last):
  File "example.py", line 17, in <module>
    sai = Spotify(username, password) # username, password of spotify premium account.
  File "/Users/coltranenadler/Documents/psotify/psotify/__init__.py", line 371, in __init__
    self.connection = Connection()
  File "/Users/coltranenadler/Documents/psotify/psotify/__init__.py", line 88, in __init__
    self._socket.connect(SPOTIFY_AP_ADDRESS)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```   

Seems as though the address changed, https://securitytrails.com/list/apex_domain/spotify.com no longer in the list of subdomains. When I try changing to another subdomain, I get this error

```
Traceback (most recent call last):
  File "example.py", line 17, in <module>
    sai = Spotify(username, password) # username, password of spotify premium account.
  File "/Users/coltranenadler/Documents/psotify/psotify/__init__.py", line 372, in __init__
    self.session = Session().connect(self.connection)
  File "/Users/coltranenadler/Documents/psotify/psotify/__init__.py", line 243, in connect
    challenge, send_key, recv_key= self._processAPHelloResponse(init_client_packet)
  File "/Users/coltranenadler/Documents/psotify/psotify/__init__.py", line 209, in _processAPHelloResponse
    prefix, size, init_server_packet= self._connection.recv_packet()
  File "/Users/coltranenadler/Documents/psotify/psotify/__init__.py", line 134, in recv_packet
    size_packet= self._socket.recv(4)
```

Assuming their protocol changed?

**Comment by jsyqrt** [comment]
`    sai = Spotify(username, password) # username, password of spotify premium account.`
This line, use your spotify username and password, then try it again.
Any problems please let me know.   :)

**Comment by annadnl** [comment]
you can send a POST request to https://apresolve.spotify.com/ - which will return a list of access points.
